openapi: 3.0.0

info:
  title: Datasourcers API
  description: API that allows external datasources to be integrated with Ferrea.
  version: 1.0.0
  contact:
    "name": "Eugenio Grimoldi"
    "url": "https://github.com/Grimoldi/ferrea-datasources"

servers:
  - url: https://ferrea.local
    description: Development local server

paths: 
  $ref: ./paths.yaml

components:
  responses: 
    $ref: ./responses.yaml

  schemas:
    $ref: ./schemas.yaml

tags: 
  - name: book
    description: Book related operations.

