openapi: 3.0.0

info:
  title: Datasourcers API
  description: API that allows external datasources to be integrated with Ferrea.
  version: 1.0.0
  contact:
    "name": "Eugenio Grimoldi"
    "url": "https://github.com/Grimoldi/ferrea-datasources"

servers:
  - url: https://ferrea.local
    description: Development local server

paths:
  /book/{isbn}:
    $ref: "./paths.yaml"

components:
  schemas:
    BookDatasource:
      $ref: "./schemas-bookdatasource.yaml#/BookDatasource"
    Error:
      $ref: "./schemas-error.yaml#/Error"

  responses: 
    NotFound:
      $ref: "./responses-not-found.yaml#/NotFound"

tags: 
  - name: book
    description: Book related operations.

