name: Run Redocly linting
description: |
  # OpenApi definition automatic update and validation.
  Create a bundle file (using a redocly), than proceed to validate it against linting.
  The bundle file will then be used from the web server.
  In case of creation/update of the bundle file, autocommit it.

  Run only if anything has been changed under the definitions or on this file itself.

on:
    push:
      branches:
        - main
      paths:
        - "oas/*.yaml"
        - ".github/workflows/redocly.yaml"

permissions:
  checks: write
  # Give the default GITHUB_TOKEN write permission to commit and push the
  # added or changed files to the repository.
  contents: write

env:
  OAS_PATH: ./oas/bundle.yaml
  SPECTRAL_IMAGE: "stoplight/spectral:6"
  REDOCLY_IMAGE: "redocly/cli:1.34.3"

jobs:
  build:
    name: Redocly linting
    runs-on: ubuntu-latest
    # continue-on-error: true
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: OAS Bundling
      id: bundling
      run: |
        {
              echo 'bundling-result<<EOF'
              echo -e "$(docker run --rm \
              --volume ${{ github.workspace }}:${{ github.workspace }} \
              --workdir ${{ github.workspace }} \
              --attach stdout \
              $REDOCLY_IMAGE \
              bundle ./oas/*.yaml --output $OAS_PATH )"
              echo ""
              echo "EOF"
          } >> $GITHUB_OUTPUT

    - name: Linting
      id: linting
      run: |
          {
              echo 'linting-result<<EOF'
              echo -e "$(docker run --rm \
              --volume ${{ github.workspace }}:${{ github.workspace }} \
              --workdir ${{ github.workspace }} \
              --attach stdout \
              $REDOCLY_IMAGE \
              lint $OAS_PATH --format github-actions)"
              echo ""
              echo "EOF"
          } >> $GITHUB_OUTPUT

    - name: Job summary
      id: markdown-summary
      run: |
        {
              echo -e "$(docker run --rm \
              --volume ${{ github.workspace }}:${{ github.workspace }} \
              --workdir ${{ github.workspace }} \
              --attach stdout \
              $REDOCLY_IMAGE \
              lint $OAS_PATH --format markdown)"
          } >> $GITHUB_STEP_SUMMARY

    - name: Commit changed bundle file if updated
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: 'Added or updated the bundle.yaml oas definition.'