name: Run Spectral linting

on:
    push:
      branches:
        - main

permissions:
  checks: write

jobs:
  build:
    name: Run Spectral
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Spectral Linting
      id: spectral-lint
      run: |
          {
              echo 'linting-result<<EOF'
              echo -e "$(docker run --rm \
              --volume ${{ github.workspace }}:${{ github.workspace }} \
              --workdir ${{ github.workspace }} \
              --attach stdout \
              stoplight/spectral:latest \
              lint ./root.oas.yaml --format github-actions)"
              echo ""
              echo "EOF"
          } >> $GITHUB_OUTPUT

    - name: Job summary          
      run: |
        ANNOTATIONS="${{ steps.spectral-lint.outputs.linting-result }}"
        echo "$ANNOTATIONS" >> "$GITHUB_ENV"
        echo "$ANNOTATIONS"

        WARNINGS=$(echo "$ANNOTATIONS" | grep warning | wc -l)
        echo "$WARNINGS" >> "$GITHUB_ENV"
        echo "$WARNINGS"

        ERRORS=$(echo "$ANNOTATIONS" | grep error | wc -l)
        echo "$ERRORS" >> "$GITHUB_ENV"
        echo "$ERRORS"

        ANNOTATIONLINES=$(echo "$ANNOTATIONS" | wc -l)
        if [ "ANNOTATIONLINES" -eq "0" ]; then
            ICON=":white_check_mark:"
        else
            ICON=":red_circle:"
        echo "$ICON" >> "$GITHUB_ENV"
        echo "$ICON"

        echo "### Spectral OAS analysis recap" >> $GITHUB_STEP_SUMMARY
        echo "| Test result | Warning | Errors |" >> $GITHUB_STEP_SUMMARY
        echo "| --- | --- | --- |" >> $GITHUB_STEP_SUMMARY
        echo "| ${{ env.ICON }} | ${{ env.WARNINGS }} | ${{ env.ERRORS }} |" >> $GITHUB_STEP_SUMMARY

    - name: Action return code
      run: |
        errors="${{ steps.spectral-lint.outputs.linting-result }}"

        if [ -z "$errors" ]; then
        # empty array list, no errors, rc = 0
        exit 0
        else
        # there are errors/warnings
        # echo them, so they can be annotated, and rc != 0
        echo "$errors"
        exit 1
        fi
