name: Run Spectral linting

on:
    push:
      branches:
        - main

permissions:
  checks: write

jobs:
  build:
    name: Run Spectral
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Spectral Linting
        id: spectral-lint
        run: |
            {
                echo 'linting-result<<EOF'
                echo -e "$(docker run --rm \
                --volume ${{ github.workspace }}:${{ github.workspace }} \
                --workdir ${{ github.workspace }} \
                --attach stdout \
                stoplight/spectral:latest \
                lint ./root.oas.yaml --format github-actions)"
                echo ""
                echo "EOF"
            } >> $GITHUB_OUTPUT

      - name: Action return code
        run: |
          errors="${{ steps.spectral-lint.outputs.linting-result }}"
          if [ -z "$errors" ]; then
            echo "$errors"
            exit 1
          else
            exit 0
          fi
