name: Run Spectral linting

on:
    push:
      branches:
        - main

permissions:
  checks: write

jobs:
  build:
    name: Run Spectral
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Spectral Linting
      id: spectral-lint
      run: |
          {
              echo 'linting-result<<EOF'
              echo -e "$(docker run --rm \
              --volume ${{ github.workspace }}:${{ github.workspace }} \
              --workdir ${{ github.workspace }} \
              --attach stdout \
              stoplight/spectral:latest \
              lint ./root.oas.yaml --format github-actions)"
              echo ""
              echo "EOF"
          } >> $GITHUB_OUTPUT

    - name: Job summary          
      run: |
        ANNOTATIONS="${{ steps.spectral-lint.outputs.linting-result }}"
        # echo "$ANNOTATIONS" >> "$GITHUB_ENV"

        WARNNR=$(echo "$ANNOTATIONS" | grep warning | wc -l)
        # echo "$WARNNR"
        # echo "WARNNR=$WARNNR" >> "$GITHUB_ENV"

        ERRNR=$(echo "$ANNOTATIONS" | grep error | wc -l)
        # echo "$ERRNR"
        # echo "ERRNR=$ERRNR" >> "$GITHUB_ENV"

        ANNOTATIONLINES=$(echo "$ANNOTATIONS" | wc -l)
        if [ "$ANNOTATIONLINES" -eq 0 ]; then
            ICON=":white_check_mark:"
        else
            ICON=":red_circle:"
        fi
        # echo "$ICON"
        # echo "$ICON" >> "$GITHUB_ENV"

        echo "### Spectral OAS analysis recap" >> $GITHUB_STEP_SUMMARY
        echo "| Test result | Warning | ERRNR |" >> $GITHUB_STEP_SUMMARY
        echo "| --- | --- | --- |" >> $GITHUB_STEP_SUMMARY
        # echo "| ${ICON} | ${WARNNR} | ${ERRNR} |" >> $GITHUB_STEP_SUMMARY

    - name: Action return code
      run: |
        ERRNR="${{ steps.spectral-lint.outputs.linting-result }}"

        if [ -z "$ERRNR" ]; then
        # empty array list, no ERRNR, rc = 0
        exit 0
        else
        # there are ERRNR/WARNNR
        # echo them, so they can be annotated, and rc != 0
        echo "$ERRNR"
        exit 1
        fi
