name: Run Spectral linting

on:
    push:
      branches:
        - main

permissions:
  checks: write

jobs:
  build:
    name: Run Spectral
    runs-on: ubuntu-latest
    steps:
      # Check out the repository
      - uses: actions/checkout@v3

      # Run Spectral
      # - uses: stoplightio/spectral-action@latest

      
      # - name: Run Spectral Lint
      #   id: spectral-lint
      #   uses: addnab/docker-run-action@v3
      #   with:
      #       image: stoplight/spectral:latest
      #       options: -v ${{ github.workspace }}:${{ github.workspace }} -w ${{ github.workspace }}
      #       run: spectral lint ./root.oas.yaml >> $GITHUB_OUTPUT
      #       # --ruleset ./docs/spectral/bundled.spectral.yml ./docs/specification/*.yaml

      - name: Spectral Linting
        id: spectral-lint
        run: |
            {
                echo 'linting-result<<EOF'
                echo -e "$(docker run --rm \
                --volume ${{ github.workspace }}:${{ github.workspace }} \
                --workdir ${{ github.workspace }} \
                --attach stdout \
                stoplight/spectral:latest \
                lint ./root.oas.yaml --format github-actions)"
                echo ""
                echo "EOF"
            } >> $GITHUB_OUTPUT

      # - name: Extract fields for annotations
      #   id: extract-fields
      #   run: |
      #       {
      #           echo 'jq-result<<EOF'
      #           echo -e "${{ steps.spectral-lint.outputs.linting-result }}" \
      #           | jq '[.[] | {message: .message, file: .source, severity: .severity, code: .code}]' -r
      #           echo ""
      #           echo "EOF"
      #       } >> $GITHUB_OUTPUT

      # - name: Test final result
      #   run: |
      #     echo "${{ steps.extract-fields.outputs.jq-result }}"
            